universe = vanilla
executable = GAnnTrainFile.py
arguments = " $(macroarguments) "
environment = KMP_LIBRARY=serial;MKL_SERIAL=yes
getenv = True
log = /tmp/tmprZ0TCg
error = logs/TRAIN_NETWORK_ALL_n70n10n1_c10_mr02_p10000_g100_rmin-25_rmax25_gsigma1_y1001_f05g09_m8000_n70n10n1_c10_mr02_p10000_g100_rmin-25_rmax25_gsigma1_y1001_f05g09_m8000-$(macroid)-$(process).err
output = logs/TRAIN_NETWORK_ALL_n70n10n1_c10_mr02_p10000_g100_rmin-25_rmax25_gsigma1_y1001_f05g09_m8000_n70n10n1_c10_mr02_p10000_g100_rmin-25_rmax25_gsigma1_y1001_f05g09_m8000-$(macroid)-$(process).out
notification = never
queue 1
