universe = vanilla
executable = FannEvaluation.py
arguments = " $(macroarguments) "
environment = KMP_LIBRARY=serial;MKL_SERIAL=yes
getenv = True
log = /tmp/tmph8DVEA
error = logs/USE_NETWORK_ALL_n70n10n1_c10_mr04_p5000_g200_rmin-25_rmax25_gsigma1_y1001_f05g09_m8000_n70n10n1_c10_mr04_p5000_g200_rmin-25_rmax25_gsigma1_y1001_f05g09_m8000-$(macroid)-$(process).err
output = logs/USE_NETWORK_ALL_n70n10n1_c10_mr04_p5000_g200_rmin-25_rmax25_gsigma1_y1001_f05g09_m8000_n70n10n1_c10_mr04_p5000_g200_rmin-25_rmax25_gsigma1_y1001_f05g09_m8000-$(macroid)-$(process).out
notification = never
queue 1
