universe = vanilla
executable = FannEvaluation.py
arguments = " $(macroarguments) "
environment = KMP_LIBRARY=serial;MKL_SERIAL=yes
getenv = True
log = /tmp/tmpRsgAC1
error = logs/USE_NETWORK_ALL_n1250n20n1_c10_mr10_p500_g20_rmin-25_rmax25_gsigma50_y1001_f05g09_m8000_n1250n20n1_c10_mr10_p500_g20_rmin-25_rmax25_gsigma50_y1001_f05g09_m8000-$(macroid)-$(process).err
output = logs/USE_NETWORK_ALL_n1250n20n1_c10_mr10_p500_g20_rmin-25_rmax25_gsigma50_y1001_f05g09_m8000_n1250n20n1_c10_mr10_p500_g20_rmin-25_rmax25_gsigma50_y1001_f05g09_m8000-$(macroid)-$(process).out
notification = never
queue 1
